### ISSUE TITLE
demo code of initialization code is wrong?

### ISSUE THREAD

**Issue by xiaodongliang** [Autodesk-Forge/autodesk.forge.designautomation#1]
The demo code of initialization is as below, but **AutodeskForgeDesignAutomation.ApiClient** is undefined.
<img width="739" alt="Screen Shot 2019-11-12 at 5 55 51 PM" src="https://user-images.githubusercontent.com/5087461/68661597-2c8ded00-0576-11ea-8846-eeb1e3058878.png">

from the SDK sample repo , it looks the correct usage is like below:

<img width="821" alt="Screen Shot 2019-11-12 at 5 56 48 PM" src="https://user-images.githubusercontent.com/5087461/68661549-197b1d00-0576-11ea-9c07-47ee7ad2bcdd.png">

**Comment by cyrillef** [comment]
AutodeskForgeDesignAutomation.ApiClient.instance
should be
AutodeskForgeDesignAutomationClient.instance

fixed in the readme, will be released for 3.0.1
