### ISSUE TITLE
No TypeScript Type Declarations

### ISSUE THREAD

**Issue by reediculous456** [Autodesk-Forge/autodesk.forge.designautomation#3]
I cannot find TypeScript Type declarations for anything in this package. The DA v2 API had them ([@types/forge-apis](https://www.npmjs.com/package/@types/forge-apis)), is there a plan to create them for the v3 API?

**Comment by dukedhx** [comment]
Yeah you can track the progress [here](https://github.com/Autodesk-Forge/autodesk.forge.designautomation/pull/4)
