### ISSUE TITLE
typescript not finding definition provided

### ISSUE THREAD

**Issue by ncunningham-stairsupplies** [Autodesk-Forge/autodesk.forge.designautomation#6]
when using this package in a typescript project, im getting a compiler error saying that the types cannot be found. i suspect this is because the index.d.ts file is not included in the package.json

**Comment by reediculous456** [comment]
@dukedhx @cyrillef I have the same issue. #4 did not resolve #3 because the index.d.ts is not listed on the package ([See Documentation](https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html#including-declarations-in-your-npm-package))

**Comment by ncunningham-stairsupplies** [comment]
It's easy enough to copy the file, but rather annoying to have to do it
